spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/inzaghibest/SpringCloudConfig
          search-paths: respo
          username: inzaghibest
          password: 7324368best
        default-label: main
  profiles: git