eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 5000
spring:
  application:
    name: service-zuul
zuul:
  routes:
    hiapi:
      path: /hiapi/**
      serviceId: eureka-client
      # 指定服务的url,Zuul就不能做负载均衡了
      # url: http://localhost:8762
      # 自己维护服务列表实现负载均衡
#      serviceId: hiapi-v1
    ribbonapi:
      path: /ribbonapi/**
      serviceId: eureka-ribbon-client
    feignapi:
      path: /feignapi/**
      serviceId: eureka-feign-client
  # 为所有API接口加上v1作为版本号前缀
  prefix: /v1
#ribbon:
#  eureka:
#    enabled: false
#hiapi-v1:
#  ribbon:
#    listOfServers: http://localhost:8762,http://localhost:8763