spring:
  application:
    name: service-auth
  datasource:
    url: jdbc:mysql://49.232.105.82:3308/spring-cloud-oauth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: A...qqq321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  servlet:
    context-path: /uaa
  port: 5000
#  redis:
#    host: 49.232.105.82
#    password: 7324368best
#    port: 6379
#    timeout: 6s #连接池超时时长
#    lettuce:
#      pool:
#        max-active: 1000 #连接池最大连接数
#        max-wait: -1ms #连接池最大阻塞等待时间
#        max-idle: 10 #连接池最大空闲连接
#        min-idle: 5 #连接池最小空闲连接
