spring:
  application:
    name: service-auth
  datasource:
    url: jdbc:mysql://49.232.105.82:3308/spring-cloud-oauth?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: A...qqq321
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  servlet:
    context-path: /auth
  port: 5001